using Domain.Enums;

namespace Application.DTOs.Sync;

public class SyncRequest
{
    /// <summary>Identifies the sending device. Shown in the UI and used to break ties.</summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// The highest change number this device has already seen. The server replies
    /// with everything above it, which is how a device that was offline catches up.
    /// </summary>
    public long SinceSeq { get; set; }

    public List<SyncOperationRequest> Operations { get; set; } = new();
}

public class SyncOperationRequest
{
    /// <summary>
    /// Generated by the client when the user acts, and kept identical across every
    /// retry. This is what makes a resend harmless: the server recognises it has
    /// already handled this exact action.
    /// </summary>
    public Guid OpId { get; set; }

    public Guid HabitId { get; set; }

    /// <summary>The day the user meant, in their own calendar.</summary>
    public DateOnly LocalDate { get; set; }

    public CheckInStatus Status { get; set; }

    /// <summary>UTC instant the user pressed the button, not when it was sent.</summary>
    public DateTime ClientUpdatedAt { get; set; }
}
